export const FETCH_GIF_REQUEST = "FETCH_GIF_REQUEST";
export const FETCH_GIF_SUCCESS = "FETCH_GIF_SUCCESS";
export const FETCH_GIF_FAILURE = "FETCH_GIF_FAILURE";
export const ADD_GIF = "ADD_GIF";
export const REMOVE_GIF = "REMOVE_GIF";
export const SET_USER_MESSAGE = "SET_USER_MESSAGE";
export const CLEAR_GIF_LIST_AND_RESULT = "CLEAR_GIF_LIST_AND_RESULT";
